// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTxHsQtZQ4RsaFUT-BnIonQ8v_VgfIaKw',
    appId: '1:75256060551:web:05838c837eb9a2f932f622',
    messagingSenderId: '75256060551',
    projectId: 'bancoapp-edc28',
    authDomain: 'bancoapp-edc28.firebaseapp.com',
    storageBucket: 'bancoapp-edc28.firebasestorage.app',
    measurementId: 'G-31CM0BS8PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPsSPH76bcznhvyHRkZg5s38RjFrf5Gw8',
    appId: '1:75256060551:android:de3a5cb008a4944532f622',
    messagingSenderId: '75256060551',
    projectId: 'bancoapp-edc28',
    storageBucket: 'bancoapp-edc28.firebasestorage.app',
  );
}
